### PR TITLE
Run evaluateJavascript on the UI thread

### LINKED ISSUE #10: Error: A WebView method was called on thread 'JavaBridge'.
### General information

* SDK/Library version: 0.1.1
* Android Version and Device: Android 7.1.1 Pixel XL Android Emulator
### Issue description

The method 'open(String url)' is called in WebviewInterface. The url is https://www.paypal.com/checkoutnow?..&useraction=commit and i get an exception in my webview.

The webview is shown inside a fragment.

java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {5891226} called on Looper (JavaBridge, tid 621) {a07812e}, FYI main Looper is Looper (main, tid 1) {5891226})
                                                                                at android.webkit.WebView.checkThread(WebView.java:2334)
                                                                                at android.webkit.WebView.evaluateJavascript(WebView.java:1036)
                                                                                at com.braintreepayments.popupbridge.PopupBridge.onBrowserSwitchResult(PopupBridge.java:132)
                                                                                at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:132)
                                                                                at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:107)
                                                                                at com.braintreepayments.popupbridge.PopupBridge.open(PopupBridge.java:148)

### PR DESCRIPTION
**Pull request by quinnjn**
Wrapping the `evaluateJavascript` in a `View#post` to make sure it is being ran on the same thread as the `WebView`.

`evaluateJavascript` (along with all the `WebView` public methods) call [`WebView#checkThread`](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/webkit/WebView.java#L1054) which checks that the method was called on the same thread as the `WebView`'s thread.

This should fix #10.

@braintree/team-dx

### CODE REVIEW

File: PopupBridge/src/main/java/com/braintreepayments/popupbridge/PopupBridge.java [hunk 1]
```diff
@@ -137,8 +137,16 @@ public void onBrowserSwitchResult(int requestCode, BrowserSwitchResult result, U
...
 
-        mWebView.evaluateJavascript(String.format("window.popupBridge.onComplete(%s, %s);", error,
-                payload), null);
+        final String postError = error;
+        final String postPayload = payload;
+
+        mWebView.post(new Runnable() {
+            @Override
+            public void run() {
+                mWebView.evaluateJavascript(String.format("window.popupBridge.onComplete(%s, %s);",
```
Comment (crookedneighbor) [inline PopupBridge/src/main/java/com/braintreepayments/popupbridge/PopupBridge.java]: I assume the same needs to be done above in the cancel case.

**Comment by quinnjn** [comment]
I can't approve my own PR but I 👍  the commit you made @crookedneighbor

File: PopupBridge/src/main/java/com/braintreepayments/popupbridge/PopupBridge.java [hunk 2]
```diff
@@ -93,18 +93,27 @@ public void onCreate(Bundle savedInstanceState) {
         setRetainInstance(true);
     }
 
+    public void runJavaScriptInWebview(final String script) {
```
Comment (lkorth) [inline PopupBridge/src/main/java/com/braintreepayments/popupbridge/PopupBridge.java]: It's WebView :) :trollface:

Comment (lkorth) [reply PopupBridge/src/main/java/com/braintreepayments/popupbridge/PopupBridge.java]: I think this should be private unless there's a use for it elsewhere.
